title: "jessevdp"
owner: ""
keywords: ""
description: ""

exclude: ["CNAME", "README"]
timezone: "Europe/Amsterdam"

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: portfolio
