title: "jessevdp"
owner: ""
keywords: ""
description: ""

links:
  instagram: "https://www.instagram.com/skillzzjesse/"
  twitter: "https://twitter.com/skillzzjesse"
  github: "https://github.com/jessevdp"
  linkedin: "https://linkedin.com/in/jessevdp"

exclude: ["CNAME", "README"]
timezone: "Europe/Amsterdam"

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: portfolio
