title: "jessevdp"
owner: "Jesse van der Pluijm"
keywords: "Programmer,Designer,Student,The Netherlands,Code,Logo,Portfolio,Work"
description: "Student, Programmer & Designer from the Netherlands"

links:
  instagram: "https://www.instagram.com/skillzzjesse/"
  twitter: "https://twitter.com/skillzzjesse"
  github: "https://github.com/jessevdp"
  linkedin: "https://linkedin.com/in/jessevdp"

exclude: ["CNAME", "README"]
timezone: "Europe/Amsterdam"

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /work/:title/
      layout: portfolio
